platform :ios,'8.0'
target 'DemoSet' do
pod 'AFNetworking','~> 3.0'
pod 'Alamofire','~> 4.7.3'
pod 'HandyJSON','~> 4.2.1'
pod 'SnapKit', '~> 3.2.0'
pod 'OpenCV', '~> 3.4.1'
pod 'FMDB', '~> 2.7.2'
pod 'FLEX', '~> 2.4.0'
pod 'Kingfisher'
use_frameworks!
end
